### ISSUE TITLE
Changing expanded value doesn't change table rows

### ISSUE THREAD

**Issue by illestrater** [Swimlane/angular-data-table#131] opened 2016-01-12 19:05 UTC
Hi, so I'm facing an issue that I'd really like to get hammered out. When I change the expanded flag to false on a parent row, it changes the state of the parent row's toggle button but does not actually collapse the child rows. In order to do so, I would have to load the data again.

Example here: http://codepen.io/anon/pen/LGjPbg

Any ideas?
Thanks for your support man!

**Comment by amcdnl** [comment] 2016-01-12 19:16
Duplicate of #3 

I've known about it since beginning, I don't personally have a use case for the tree so its not got any TLC. I kinda just threw it in there. I'd be more than happy to accept any PRs, code you need to start looking at is here: https://github.com/Swimlane/angular-data-table/blob/master/src/components/body/BodyController.js#L165

**Closed as completed by amcdnl** 2016-01-12 19:16 UTC
Labels: duplicate
