### ISSUE TITLE
Enhancement request: onRowDblClick

### ISSUE THREAD

**Issue by wmichaelfeltman** [Swimlane/angular-data-table#66] opened 2015-08-28 14:22 UTC
I am using angular-data-table with much success. Thanks for doing this.

I could use a double click event for a row. Are there any plans for one?

**Comment by amcdnl** [comment] 2015-08-28 14:27
Dupe of #54.

**Closed as completed by amcdnl** 2015-08-28 14:27 UTC

**Comment by wmichaelfeltman** [comment] 2015-08-28 15:23
Sorry. Thanks. I'm still getting used to this whole github thing.
