### ISSUE TITLE
when using ./release/dataTable.js there is still babelHelpers is not defined

### ISSUE THREAD

**Issue by kuzman** [Swimlane/angular-data-table#112] opened 2015-12-13 20:30 UTC
Uncaught ReferenceError: babelHelpers is not defined
(anonymous function) @ dataTable.js:81
(anonymous function) @ dataTable.js:143
(anonymous function) @ dataTable.js:16
(anonymous function) @ dataTable.js:19

**Comment by amcdnl** [comment] 2015-12-15 02:29
duplicate of #111

**Closed as completed by amcdnl** 2015-12-15 02:29 UTC

**Comment by ghost** [comment] 2016-04-25 13:41
This issue is not a duplicate of #111.
When we add your dependency to our projects, regardless of the browser, we have this error.

You are using the babel helpers in your code, but somehow it is still present in the release file.

**Comment by amcdnl** [comment] 2016-04-25 14:05
You don't have to use the babel compiled version.`./release/dataTable.es6.js - Raw ES6 Version.`

**Comment by ghost** [comment] 2016-04-25 15:41
Well, the purpose of Babel is to compile ES6 syntax into a JavaScript we can use write now.
I tried to use the ES6 instead of the compiled version and the browser doesn't recognize the syntax.
So yes, we have to use the compiled version.

We shouldn't have this error, it comes out of the box when you install the dependency via bower.
Do you have any idea how to fix it?
