### ISSUE TITLE
The demo site does not work.

### ISSUE THREAD

**Issue by mrtinkz** [Swimlane/angular-data-table#87] opened 2015-09-29 22:12 UTC
Hi,

Looks like the demo http://swimlane.github.io/angular-data-table/ is not working. I do not see the grid content, not sure but below is the error i see in my console. 

```
at XMLHttpRequest.D.onload (angular.min.js:86)(anonymous function) @ angular.min.js:102
```

**Comment by amcdnl** [comment] 2015-09-30 11:24
dupe of #52

**Closed as completed by amcdnl** 2015-09-30 11:24 UTC

**Comment by mrtinkz** [comment] 2015-10-03 14:29
Got it, thanks
