### ISSUE TITLE
Error with  adding dataTable.helpers.min.js  

### ISSUE THREAD

**Issue by penumatsasiva** [Swimlane/angular-data-table#160] opened 2016-04-02 16:30 UTC
hii
    when i add this dependency(dataTable.helpers.min.js) in  main source folder everything is  working good  and my  build is running fine and iam not getting any errors. but  when iam  running  my gulp build through  dist iam getting this error .

dataTable.helpers.min.jsevents.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: scripts\vendor.js: error: couldn't process source due to parse error
Unexpected token (158445:0)

 plz  help me in this iisue

**Comment by amcdnl** [comment] 2016-04-04 12:25
Dupe of https://github.com/Swimlane/angular-data-table/issues/90

**Closed as completed by amcdnl** 2016-04-04 12:25 UTC
