### ISSUE TITLE
dataTableHelper.min.js is giving error

### ISSUE THREAD

**Issue by samit2015** [Swimlane/angular-data-table#111] opened 2015-12-08 17:10 UTC
HI, I m trying to create a sample app with angular-min.js 1.4.8 with  dataTableHelper.min.js and I m getting this error on IE.

TypeError: Object doesn't support property or method 'assign'
   at e (http://localhost:9080/TestApplication/js/dataTable.helpers.min.js:1365:29)
   at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:39:87)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:80:143)
   at L (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:61:134)
   at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:326)
   at L (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:61:439)
   at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:326)
   at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:349)
   at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:349)
   at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:349)
Can any1 plz help me on this?

Thanks

**Comment by amcdnl** [comment] 2015-12-08 17:14
This is an issue with the Babel helpers, not nesc this project. Can you make a demo to show it breaking?

**Comment by samit2015** [comment] 2015-12-08 17:16
Thanks for replying...I m not using babel...I simply downloaded those 2 js and 1 html and 1 main js file...Things are working pretty good on FireFox but IE 11 giving error

**Comment by samit2015** [comment] 2015-12-09 06:51
Here is attached sample code....plz extract n run index.html to see issue (F12 on IE). 

Also, I want to if angular-data-table supports IE or not?
[WebContent.zip](https://github.com/Swimlane/angular-data-table/files/56437/WebContent.zip)

**Comment by amcdnl** [comment] 2015-12-09 11:59
It does support ie 11+

**Comment by samit2015** [comment] 2015-12-09 12:47
Thanks ....Can u plz look at attached zip file and help me to figure it out?

**Comment by samit2015** [comment] 2015-12-11 12:51
Can I expect some help on this? else u can close it.

**Comment by amcdnl** [comment] 2015-12-15 02:29
@marjan-georgiev can u provide feedback?

**Comment by amcdnl** [comment] 2015-12-30 14:07
dupe of Internet explorer complains about Object.assign use #114 opened 13 days ago by pan-henryk

**Closed as completed by amcdnl** 2015-12-30 14:07 UTC

**Comment by jesben** [comment] 2016-02-22 15:56
To get it work in IE, I use es6-shim - https://github.com/paulmillr/es6-shim
