### ISSUE TITLE
Many errors run on chrome 45.0.2454.101 (64-bit) on mac os x

### ISSUE THREAD

**Issue by developerworks** [Swimlane/angular-data-table#88] opened 2015-10-05 17:13 UTC
In the chrome 45.0.2454.101 (64-bit) on mac os x , access page: `http://swimlane.github.io/angular-data-table/` thrown the following errors:

``` js
icon $default:menu not found
angular.js:12314 icon $default:menu not found
dataTable.js:81 Uncaught ReferenceError: babelHelpers is not defined(anonymous function) @ dataTable.js:81(anonymous function) @ dataTable.js:149Array.(anonymous function).thisArg @ dataTable.js:16(anonymous function) @ dataTable.js:19
angular.js:11607 TypeError: Cannot read property 'length' of undefined
    at DataTableController.transposeColumnDefaults (https://cdn.rawgit.com/Swimlane/angular-data-table/gh-pages/lib/dataTable.helpers.js:1964:51)
    at pre (https://cdn.rawgit.com/Swimlane/angular-data-table/gh-pages/lib/dataTable.helpers.js:2157:18)
    at Z (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:70:149)
    at A (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:59:14)
    at g (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:51:299)
    at A (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:59:147)
    at g (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:51:299)
    at g (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:51:316)
    at http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:50:415
    at http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:18:8 <div class="material dt ng-scope" ng-class="dt.tableCss()" data-column-id="5612ae8ccd0bd824695662ef" options="options" rows="data">(anonymous function) @ angular.js:11607b.$get @ angular.js:8557Z @ angular.js:8221A @ angular.js:7708g @ angular.js:7078A @ angular.js:7724g @ angular.js:7078g @ angular.js:7081(anonymous function) @ angular.js:6957(anonymous function) @ angular.js:1450c.$get.l.$eval @ angular.js:14401c.$get.l.$apply @ angular.js:14500(anonymous function) @ angular.js:1448e @ angular.js:4185d @ angular.js:1446tc @ angular.js:1466Jd @ angular.js:1360(anonymous function) @ angular.js:26176a @ angular.js:2744c @ angular.js:3014
angular.js:11607 TypeError: Cannot read property 'columns' of undefined
    at new BodyController (dataTable.helpers.js:800)
    at Object.e [as invoke] (angular.js:4185)
    at b.$get.w.instance (angular.js:8454)
    at angular.js:7700
    at s (angular.js:331)
    at A (angular.js:7699)
    at g (angular.js:7078)
    at A (angular.js:7724)
    at g (angular.js:7078)
    at A (angular.js:7724)(anonymous function) @ angular.js:11607b.$get @ angular.js:8557c.$get.l.$apply @ angular.js:14502(anonymous function) @ angular.js:1448e @ angular.js:4185d @ angular.js:1446tc @ angular.js:1466Jd @ angular.js:1360(anonymous function) @ angular.js:26176a @ angular.js:2744c @ angular.js:3014
angular.js:11607 TypeError: Cannot read property 'length' of undefined
    at Object.fn (dataTable.helpers.js:1922)
    at l.c.$get.l.$digest (angular.js:14243)
    at l.c.$get.l.$apply (angular.js:14506)
    at angular.js:1448
    at Object.e [as invoke] (angular.js:4185)
    at d (angular.js:1446)
    at tc (angular.js:1466)
    at Jd (angular.js:1360)
    at angular.js:26176
    at HTMLDocument.a (angular.js:2744)(anonymous function) @ angular.js:11607b.$get @ angular.js:8557c.$get.l.$digest @ angular.js:14261c.$get.l.$apply @ angular.js:14506(anonymous function) @ angular.js:1448e @ angular.js:4185d @ angular.js:1446tc @ angular.js:1466Jd @ angular.js:1360(anonymous function) @ angular.js:26176a @ angular.js:2744c @ angular.js:3014
angular.js:11607 TypeError: Cannot read property 'center' of undefined
    at HeaderController.stylesByGroup (dataTable.helpers.js:1320)
    at ib.functionCall (angular.js:12345)
    at Object.<anonymous> (angular.js:12851)
    at l.c.$get.l.$digest (angular.js:14235)
    at l.c.$get.l.$apply (angular.js:14506)
    at angular.js:1448
    at Object.e [as invoke] (angular.js:4185)
    at d (angular.js:1446)
    at tc (angular.js:1466)
    at Jd (angular.js:1360)(anonymous function) @ angular.js:11607b.$get @ angular.js:8557c.$get.l.$digest @ angular.js:14261c.$get.l.$apply @ angular.js:14506(anonymous function) @ angular.js:1448e @ angular.js:4185d @ angular.js:1446tc @ angular.js:1466Jd @ angular.js:1360(anonymous function) @ angular.js:26176a @ angular.js:2744c @ angular.js:3014
angular.js:11607 TypeError: Cannot read property 'total' of undefined
    at HeaderController.innerStyles (dataTable.helpers.js:1306)
    at ib.functionCall (angular.js:12345)
    at Object.<anonymous> (angular.js:12851)
    at l.c.$get.l.$digest (angular.js:14235)
    at l.c.$get.l.$apply (angular.js:14506)
    at angular.js:1448
    at Object.e [as invoke] (angular.js:4185)
    at d (angular.js:1446)
    at tc (angular.js:1466)
    at Jd (angular.js:1360)(anonymous function) @ angular.js:11607b.$get @ angular.js:8557c.$get.l.$digest @ angular.js:14261c.$get.l.$apply @ angular.js:14506(anonymous function) @ angular.js:1448e @ angular.js:4185d @ angular.js:1446tc @ angular.js:1466Jd @ angular.js:1360(anonymous function) @ angular.js:26176a @ angular.js:2744c @ angular.js:3014
angular.js:11607 TypeError: Cannot read property 'internal' of undefined
    at HeaderController.styles (dataTable.helpers.js:1298)
    at ib.functionCall (angular.js:12345)
    at Object.<anonymous> (angular.js:12851)
    at l.c.$get.l.$digest (angular.js:14235)
    at l.c.$get.l.$apply (angular.js:14506)
    at angular.js:1448
    at Object.e [as invoke] (angular.js:4185)
    at d (angular.js:1446)
    at tc (angular.js:1466)
    at Jd (angular.js:1360)(anonymous function) @ angular.js:11607b.$get @ angular.js:8557c.$get.l.$digest @ angular.js:14261c.$get.l.$apply @ angular.js:14506(anonymous function) @ angular.js:1448e @ angular.js:4185d @ angular.js:1446tc @ angular.js:1466Jd @ angular.js:1360(anonymous function) @ angular.js:26176a @ angular.js:2744c @ angular.js:3014
angular.js:11607 TypeError: Cannot read property 'center' of undefined
    at HeaderController.stylesByGroup (dataTable.helpers.js:1320)
    at ib.functionCall (angular.js:12345)
    at Object.<anonymous> (angular.js:12851)
    at l.c.$get.l.$digest (angular.js:14235)
    at l.c.$get.l.$apply (angular.js:14506)
    at angular.js:1448
    at Object.e [as invoke] (angular.js:4185)
    at d (angular.js:1446)
    at tc (angular.js:1466)
    at Jd (angular.js:1360)(anonymous function) @ angular.js:11607b.$get @ angular.js:8557c.$get.l.$digest @ angular.js:14261c.$get.l.$apply @ angular.js:14506(anonymous function) @ angular.js:1448e @ angular.js:4185d @ angular.js:1446tc @ angular.js:1466Jd @ angular.js:1360(anonymous function) @ angular.js:26176a @ angular.js:2744c @ angular.js:3014
angular.js:11607 TypeError: Cannot read property 'center' of undefined
    at HeaderController.stylesByGroup (dataTable.helpers.js:1320)
    at ib.functionCall (angular.js:12345)
    at Object.<anonymous> (angular.js:12851)
    at l.c.$get.l.$digest (angular.js:14235)
    at l.c.$get.l.$apply (angular.js:14506)
    at l (angular.js:9659)
    at S (angular.js:9849)
    at XMLHttpRequest.D.onload (angular.js:9790)(anonymous function) @ angular.js:11607b.$get @ angular.js:8557c.$get.l.$digest @ angular.js:14261c.$get.l.$apply @ angular.js:14506l @ angular.js:9659S @ angular.js:9849D.onload @ angular.js:9790
angular.js:11607 TypeError: Cannot read property 'total' of undefined
    at HeaderController.innerStyles (dataTable.helpers.js:1306)
    at ib.functionCall (angular.js:12345)
    at Object.<anonymous> (angular.js:12851)
    at l.c.$get.l.$digest (angular.js:14235)
    at l.c.$get.l.$apply (angular.js:14506)
    at l (angular.js:9659)
    at S (angular.js:9849)
    at XMLHttpRequest.D.onload (angular.js:9790)(anonymous function) @ angular.js:11607b.$get @ angular.js:8557c.$get.l.$digest @ angular.js:14261c.$get.l.$apply @ angular.js:14506l @ angular.js:9659S @ angular.js:9849D.onload @ angular.js:9790
angular.js:11607 TypeError: Cannot read property 'internal' of undefined
    at HeaderController.styles (dataTable.helpers.js:1298)
    at ib.functionCall (angular.js:12345)
    at Object.<anonymous> (angular.js:12851)
    at l.c.$get.l.$digest (angular.js:14235)
    at l.c.$get.l.$apply (angular.js:14506)
    at l (angular.js:9659)
    at S (angular.js:9849)
    at XMLHttpRequest.D.onload (angular.js:9790)
```

**Comment by amcdnl** [comment] 2015-10-22 13:16
dupe of #90

**Closed as completed by amcdnl** 2015-10-22 13:16 UTC
